#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 RIME 聯想索引的 Lua 表檔：
  讀 ms_quick_phrases.dict.yaml（text<TAB>code，按詞頻 by_weight 排列）
  -> 輸出 lua/ms_quick_index.lua：return { ["首字"] = {詞1, 詞2, ...}, ... }
     組內順序保留來源詞頻順序（最常見的接續詞排最前，對應 Shift+1）。
"""
import os
import sys

APP_RIME = os.path.expandvars(r"%APPDATA%\Rime")
SRC = os.path.join(APP_RIME, "ms_quick_phrases.dict.yaml")
OUT = os.path.join(APP_RIME, "lua", "ms_quick_index.lua")

def parse_first_char(s: str) -> str:
    # 取第一個 Unicode 字元（含中文）
    return s[0] if s else ""

def main():
    if not os.path.exists(SRC):
        print(f"ERROR: 找不到詞組詞典 {SRC}")
        sys.exit(1)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)

    idx = {}          # first_char -> list[word]
    order = []        # 保持首字出現順序（美觀/穩定）
    in_body = False
    dash_count = 0
    count = 0
    with open(SRC, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.strip() == "---":
                dash_count += 1
                # RIME 詞典：第 1 個 --- 是 frontmatter 起，第 2 個 --- 才是內文起
                if dash_count == 2:
                    in_body = True
                continue
            if line.strip() == "...":
                in_body = False
                continue
            if not in_body:
                continue
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 2:
                # 也允許空格分隔
                parts = line.split(None, 1)
            if len(parts) < 2:
                continue
            text = parts[0].strip()
            if not text or len(text) < 2:
                continue
            head = parse_first_char(text)
            if head not in idx:
                idx[head] = []
                order.append(head)
            idx[head].append(text)
            count += 1

    # 寫入 Lua 表
    lines = []
    lines.append("-- Auto-generated by gen_ms_quick_index.py")
    lines.append("-- 首字 -> 聯想詞清單（組內保留來源詞頻順序：最常見排最前）")
    lines.append("return {")
    for head in order:
        words = idx[head]
        # 每行約 6 個詞，便於閱讀
        chunk = []
        arr = []
        for w in words:
            # 跳過含雙引號/反斜線（極罕見），簡單轉義
            safe = w.replace("\\", "\\\\").replace('"', '\\"')
            arr.append('"' + safe + '"')
        # 單行輸出（詞多也無妨，Lua 不關心換行）
        lines.append('  ["%s"] = {%s},' % (head, ", ".join(arr)))
    lines.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    total_chars = len(order)
    print(f"OK: 解析 {count} 條詞組，{total_chars} 個首字")
    print(f"輸出 -> {OUT}  ({os.path.getsize(OUT)} bytes)")
    # 抽樣檢查
    for demo in ("什", "我", "你", "中"):
        if demo in idx:
            print(f"  示範 [{demo}] 前 5: {idx[demo][:5]}")

if __name__ == "__main__":
    main()
